export interface Player {
  id: string
  name: string
  number: number
  position: string
  team: string
  teamKorean: string
  stats?: {
    // 타자 통계
    avg?: number
    hits?: number
    homeRuns?: number
    rbi?: number
    runs?: number
    // 투수 통계
    era?: number
    wins?: number
    losses?: number
    saves?: number
    strikeouts?: number
  }
}

export const teams = [
  { code: "LG", name: "LG 트윈스", korean: "LG" },
  { code: "HAN", name: "한화 이글스", korean: "한화" },
  { code: "SSG", name: "SSG 랜더스", korean: "SSG" },
  { code: "KT", name: "KT 위즈", korean: "KT" },
  { code: "SAM", name: "삼성 라이온즈", korean: "삼성" },
  { code: "LOT", name: "롯데 자이언츠", korean: "롯데" },
  { code: "NC", name: "NC 다이노스", korean: "NC" },
  { code: "KIA", name: "KIA 타이거즈", korean: "KIA" },
  { code: "DOO", name: "두산 베어스", korean: "두산" },
  { code: "KIW", name: "키움 히어로즈", korean: "키움" },
]

export const players: Player[] = [
  // LG 트윈스
  {
    id: "lg-lim-chan-gyu",
    name: "임찬규",
    number: 1,
    position: "투수",
    team: "LG",
    teamKorean: "LG",
    stats: { era: 3.45, wins: 12, losses: 8, strikeouts: 145 },
  },
  {
    id: "lg-ham-deok-ju",
    name: "함덕주",
    number: 11,
    position: "투수",
    team: "LG",
    teamKorean: "LG",
    stats: { era: 4.12, wins: 8, losses: 6, strikeouts: 98 },
  },
  {
    id: "lg-song-seung-gi",
    name: "송승기",
    number: 13,
    position: "투수",
    team: "LG",
    teamKorean: "LG",
    stats: { era: 3.89, wins: 9, losses: 7, strikeouts: 112 },
  },
  {
    id: "lg-park-si-won",
    name: "박시원",
    number: 19,
    position: "투수",
    team: "LG",
    teamKorean: "LG",
    stats: { era: 2.98, wins: 15, losses: 4, strikeouts: 167 },
  },
  {
    id: "lg-bae-jae-jun",
    name: "배재준",
    number: 25,
    position: "투수",
    team: "LG",
    teamKorean: "LG",
    stats: { era: 4.56, wins: 6, losses: 9, strikeouts: 87 },
  },
  {
    id: "lg-son-ju-young",
    name: "손주영",
    number: 29,
    position: "투수",
    team: "LG",
    teamKorean: "LG",
    stats: { era: 3.67, wins: 10, losses: 5, strikeouts: 134 },
  },
  {
    id: "lg-tollhurst",
    name: "톨허스트",
    number: 30,
    position: "투수",
    team: "LG",
    teamKorean: "LG",
    stats: { era: 3.21, wins: 11, losses: 6, strikeouts: 156 },
  },
  {
    id: "lg-lee-jung-yong",
    name: "이정용",
    number: 31,
    position: "투수",
    team: "LG",
    teamKorean: "LG",
    stats: { era: 4.23, wins: 7, losses: 8, strikeouts: 92 },
  },
  {
    id: "lg-lee-ji-gang",
    name: "이지강",
    number: 32,
    position: "투수",
    team: "LG",
    teamKorean: "LG",
    stats: { era: 3.78, wins: 8, losses: 7, strikeouts: 105 },
  },
  {
    id: "lg-park-myung-geun",
    name: "박명근",
    number: 39,
    position: "투수",
    team: "LG",
    teamKorean: "LG",
    stats: { era: 4.01, wins: 9, losses: 6, strikeouts: 118 },
  },
  {
    id: "lg-lee-jong-jun",
    name: "이종준",
    number: 40,
    position: "투수",
    team: "LG",
    teamKorean: "LG",
    stats: { era: 3.54, wins: 12, losses: 7, strikeouts: 142 },
  },
  {
    id: "lg-kim-jin-sung",
    name: "김진성",
    number: 42,
    position: "투수",
    team: "LG",
    teamKorean: "LG",
    stats: { era: 4.34, wins: 5, losses: 10, strikeouts: 78 },
  },
  {
    id: "lg-kim-jin-su",
    name: "김진수",
    number: 45,
    position: "투수",
    team: "LG",
    teamKorean: "LG",
    stats: { era: 3.92, wins: 8, losses: 8, strikeouts: 101 },
  },
  {
    id: "lg-chirinos",
    name: "치리노스",
    number: 46,
    position: "투수",
    team: "LG",
    teamKorean: "LG",
    stats: { era: 2.87, wins: 14, losses: 5, strikeouts: 178 },
  },
  {
    id: "lg-yu-young-chan",
    name: "유영찬",
    number: 54,
    position: "투수",
    team: "LG",
    teamKorean: "LG",
    stats: { era: 4.67, wins: 4, losses: 11, strikeouts: 65 },
  },
  {
    id: "lg-kim-young-woo",
    name: "김영우",
    number: 67,
    position: "투수",
    team: "LG",
    teamKorean: "LG",
    stats: { era: 3.45, wins: 10, losses: 6, strikeouts: 125 },
  },

  {
    id: "lg-lee-ju-heon",
    name: "이주헌",
    number: 26,
    position: "포수",
    team: "LG",
    teamKorean: "LG",
    stats: { avg: 0.267, hits: 89, homeRuns: 12, rbi: 45, runs: 38 },
  },
  {
    id: "lg-park-dong-won",
    name: "박동원",
    number: 27,
    position: "포수",
    team: "LG",
    teamKorean: "LG",
    stats: { avg: 0.245, hits: 67, homeRuns: 8, rbi: 32, runs: 28 },
  },
  {
    id: "lg-kim-sung-woo",
    name: "김성우",
    number: 44,
    position: "포수",
    team: "LG",
    teamKorean: "LG",
    stats: { avg: 0.289, hits: 95, homeRuns: 15, rbi: 52, runs: 41 },
  },

  {
    id: "lg-oh-ji-hwan",
    name: "오지환",
    number: 10,
    position: "내야수",
    team: "LG",
    teamKorean: "LG",
    stats: { avg: 0.312, hits: 145, homeRuns: 28, rbi: 89, runs: 78 },
  },
  {
    id: "lg-moon-bo-kyung",
    name: "문보경",
    number: 2,
    position: "내야수",
    team: "LG",
    teamKorean: "LG",
    stats: { avg: 0.278, hits: 98, homeRuns: 18, rbi: 56, runs: 52 },
  },
  {
    id: "lg-austin",
    name: "오스틴",
    number: 23,
    position: "내야수",
    team: "LG",
    teamKorean: "LG",
    stats: { avg: 0.295, hits: 132, homeRuns: 35, rbi: 98, runs: 67 },
  },
  {
    id: "lg-shin-min-jae",
    name: "신민재",
    number: 4,
    position: "내야수",
    team: "LG",
    teamKorean: "LG",
    stats: { avg: 0.256, hits: 76, homeRuns: 9, rbi: 34, runs: 41 },
  },
  {
    id: "lg-cheon-sung-ho",
    name: "천성호",
    number: 59,
    position: "내야수",
    team: "LG",
    teamKorean: "LG",
    stats: { avg: 0.234, hits: 54, homeRuns: 6, rbi: 28, runs: 32 },
  },
  {
    id: "lg-koo-bon-hyuk",
    name: "구본혁",
    number: 6,
    position: "내야수",
    team: "LG",
    teamKorean: "LG",
    stats: { avg: 0.289, hits: 112, homeRuns: 14, rbi: 67, runs: 58 },
  },
  {
    id: "lg-lee-young-bin",
    name: "이영빈",
    number: 7,
    position: "내야수",
    team: "LG",
    teamKorean: "LG",
    stats: { avg: 0.267, hits: 89, homeRuns: 11, rbi: 43, runs: 49 },
  },

  {
    id: "lg-park-hae-min",
    name: "박해민",
    number: 17,
    position: "외야수",
    team: "LG",
    teamKorean: "LG",
    stats: { avg: 0.301, hits: 134, homeRuns: 22, rbi: 71, runs: 82 },
  },
  {
    id: "lg-kim-hyun-soo",
    name: "김현수",
    number: 22,
    position: "외야수",
    team: "LG",
    teamKorean: "LG",
    stats: { avg: 0.318, hits: 156, homeRuns: 31, rbi: 95, runs: 89 },
  },
  {
    id: "lg-choi-won-young",
    name: "최원영",
    number: 3,
    position: "외야수",
    team: "LG",
    teamKorean: "LG",
    stats: { avg: 0.245, hits: 67, homeRuns: 8, rbi: 29, runs: 35 },
  },
  {
    id: "lg-choi-seung-min",
    name: "최승민",
    number: 62,
    position: "외야수",
    team: "LG",
    teamKorean: "LG",
    stats: { avg: 0.278, hits: 98, homeRuns: 15, rbi: 54, runs: 61 },
  },
  {
    id: "lg-park-gwan-woo",
    name: "박관우",
    number: 64,
    position: "외야수",
    team: "LG",
    teamKorean: "LG",
    stats: { avg: 0.234, hits: 56, homeRuns: 7, rbi: 26, runs: 31 },
  },
  {
    id: "lg-kim-hyun-jong",
    name: "김현종",
    number: 66,
    position: "외야수",
    team: "LG",
    teamKorean: "LG",
    stats: { avg: 0.289, hits: 123, homeRuns: 19, rbi: 68, runs: 74 },
  },
  {
    id: "lg-moon-sung-ju",
    name: "문성주",
    number: 8,
    position: "외야수",
    team: "LG",
    teamKorean: "LG",
    stats: { avg: 0.256, hits: 78, homeRuns: 12, rbi: 41, runs: 45 },
  },

  // 한화 이글스
  {
    id: "han-moon-dong-ju",
    name: "문동주",
    number: 1,
    position: "투수",
    team: "HAN",
    teamKorean: "한화",
    stats: { era: 3.21, wins: 13, losses: 7, strikeouts: 158 },
  },
  {
    id: "han-eom-sang-baek",
    name: "엄상백",
    number: 11,
    position: "투수",
    team: "HAN",
    teamKorean: "한화",
    stats: { era: 4.12, wins: 8, losses: 9, strikeouts: 102 },
  },
  {
    id: "han-hwang-jun-seo",
    name: "황준서",
    number: 29,
    position: "투수",
    team: "HAN",
    teamKorean: "한화",
    stats: { era: 3.78, wins: 10, losses: 6, strikeouts: 134 },
  },
  {
    id: "han-ponce",
    name: "폰세",
    number: 30,
    position: "투수",
    team: "HAN",
    teamKorean: "한화",
    stats: { era: 2.95, wins: 15, losses: 4, strikeouts: 172 },
  },
  {
    id: "han-kim-jong-soo",
    name: "김종수",
    number: 38,
    position: "투수",
    team: "HAN",
    teamKorean: "한화",
    stats: { era: 4.45, wins: 6, losses: 10, strikeouts: 89 },
  },
  {
    id: "han-kang-jae-min",
    name: "강재민",
    number: 39,
    position: "투수",
    team: "HAN",
    teamKorean: "한화",
    stats: { era: 3.67, wins: 9, losses: 7, strikeouts: 118 },
  },
  {
    id: "han-jung-woo-ju",
    name: "정우주",
    number: 43,
    position: "투수",
    team: "HAN",
    teamKorean: "한화",
    stats: { era: 4.01, wins: 7, losses: 8, strikeouts: 95 },
  },
  {
    id: "han-kim-seo-hyun",
    name: "김서현",
    number: 44,
    position: "투수",
    team: "HAN",
    teamKorean: "한화",
    stats: { era: 3.54, wins: 11, losses: 5, strikeouts: 142 },
  },
  {
    id: "han-kim-beom-soo",
    name: "김범수",
    number: 47,
    position: "투수",
    team: "HAN",
    teamKorean: "한화",
    stats: { era: 4.23, wins: 5, losses: 11, strikeouts: 76 },
  },
  {
    id: "han-yoon-san-heum",
    name: "윤산흠",
    number: 49,
    position: "투수",
    team: "HAN",
    teamKorean: "한화",
    stats: { era: 3.89, wins: 8, losses: 7, strikeouts: 108 },
  },
  {
    id: "han-weiss",
    name: "와이스",
    number: 55,
    position: "투수",
    team: "HAN",
    teamKorean: "한화",
    stats: { era: 3.12, wins: 12, losses: 6, strikeouts: 165 },
  },
  {
    id: "han-park-sang-won",
    name: "박상원",
    number: 58,
    position: "투수",
    team: "HAN",
    teamKorean: "한화",
    stats: { era: 4.56, wins: 4, losses: 12, strikeouts: 67 },
  },
  {
    id: "han-ju-hyun-sang",
    name: "주현상",
    number: 66,
    position: "투수",
    team: "HAN",
    teamKorean: "한화",
    stats: { era: 3.78, wins: 9, losses: 8, strikeouts: 125 },
  },
  {
    id: "han-cho-dong-wook",
    name: "조동욱",
    number: 68,
    position: "투수",
    team: "HAN",
    teamKorean: "한화",
    stats: { era: 4.34, wins: 6, losses: 9, strikeouts: 82 },
  },
  {
    id: "han-ryu-hyun-jin",
    name: "류현진",
    number: 99,
    position: "투수",
    team: "HAN",
    teamKorean: "한화",
    stats: { era: 2.76, wins: 18, losses: 3, strikeouts: 189 },
  },

  {
    id: "han-choi-jae-hoon",
    name: "최재훈",
    number: 13,
    position: "포수",
    team: "HAN",
    teamKorean: "한화",
    stats: { avg: 0.278, hits: 95, homeRuns: 14, rbi: 48, runs: 42 },
  },
  {
    id: "han-lee-jae-won",
    name: "이재원",
    number: 20,
    position: "포수",
    team: "HAN",
    teamKorean: "한화",
    stats: { avg: 0.245, hits: 67, homeRuns: 9, rbi: 35, runs: 29 },
  },
  {
    id: "han-heo-in-seo",
    name: "허인서",
    number: 59,
    position: "포수",
    team: "HAN",
    teamKorean: "한화",
    stats: { avg: 0.289, hits: 112, homeRuns: 16, rbi: 58, runs: 51 },
  },

  {
    id: "han-ha-ju-seok",
    name: "하주석",
    number: 16,
    position: "내야수",
    team: "HAN",
    teamKorean: "한화",
    stats: { avg: 0.301, hits: 134, homeRuns: 25, rbi: 78, runs: 69 },
  },
  {
    id: "han-sim-woo-jun",
    name: "심우준",
    number: 2,
    position: "내야수",
    team: "HAN",
    teamKorean: "한화",
    stats: { avg: 0.267, hits: 89, homeRuns: 12, rbi: 45, runs: 52 },
  },
  {
    id: "han-chae-eun-sung",
    name: "채은성",
    number: 22,
    position: "내야수",
    team: "HAN",
    teamKorean: "한화",
    stats: { avg: 0.289, hits: 123, homeRuns: 18, rbi: 67, runs: 74 },
  },
  {
    id: "han-ahn-chi-hong",
    name: "안치홍",
    number: 3,
    position: "내야수",
    team: "HAN",
    teamKorean: "한화",
    stats: { avg: 0.312, hits: 145, homeRuns: 32, rbi: 95, runs: 82 },
  },
  {
    id: "han-moon-hyun-bin",
    name: "문현빈",
    number: 51,
    position: "내야수",
    team: "HAN",
    teamKorean: "한화",
    stats: { avg: 0.234, hits: 56, homeRuns: 7, rbi: 28, runs: 35 },
  },
  {
    id: "han-lee-do-yoon",
    name: "이도윤",
    number: 7,
    position: "내야수",
    team: "HAN",
    teamKorean: "한화",
    stats: { avg: 0.278, hits: 98, homeRuns: 15, rbi: 54, runs: 61 },
  },
  {
    id: "han-noh-si-hwan",
    name: "노시환",
    number: 8,
    position: "내야수",
    team: "HAN",
    teamKorean: "한화",
    stats: { avg: 0.295, hits: 132, homeRuns: 29, rbi: 89, runs: 76 },
  },
  {
    id: "han-hwang-young-mook",
    name: "황영묵",
    number: 95,
    position: "내야수",
    team: "HAN",
    teamKorean: "한화",
    stats: { avg: 0.245, hits: 67, homeRuns: 8, rbi: 32, runs: 38 },
  },

  {
    id: "han-riverato",
    name: "리베라토",
    number: 0,
    position: "외야수",
    team: "HAN",
    teamKorean: "한화",
    stats: { avg: 0.318, hits: 156, homeRuns: 35, rbi: 102, runs: 89 },
  },
  {
    id: "han-lee-jin-young",
    name: "이진영",
    number: 10,
    position: "외야수",
    team: "HAN",
    teamKorean: "한화",
    stats: { avg: 0.267, hits: 89, homeRuns: 14, rbi: 48, runs: 55 },
  },
  {
    id: "han-kim-tae-yeon",
    name: "김태연",
    number: 25,
    position: "외야수",
    team: "HAN",
    teamKorean: "한화",
    stats: { avg: 0.289, hits: 123, homeRuns: 21, rbi: 72, runs: 68 },
  },
  {
    id: "han-son-ah-seop",
    name: "손아섭",
    number: 31,
    position: "외야수",
    team: "HAN",
    teamKorean: "한화",
    stats: { avg: 0.234, hits: 56, homeRuns: 9, rbi: 31, runs: 42 },
  },
  {
    id: "han-choi-in-ho",
    name: "최인호",
    number: 41,
    position: "외야수",
    team: "HAN",
    teamKorean: "한화",
    stats: { avg: 0.278, hits: 98, homeRuns: 16, rbi: 58, runs: 64 },
  },
  {
    id: "han-lee-won-seok",
    name: "이원석",
    number: 50,
    position: "외야수",
    team: "HAN",
    teamKorean: "한화",
    stats: { avg: 0.256, hits: 78, homeRuns: 11, rbi: 41, runs: 49 },
  },
  {
    id: "han-lee-sang-hyuk",
    name: "이상혁",
    number: 9,
    position: "외야수",
    team: "HAN",
    teamKorean: "한화",
    stats: { avg: 0.301, hits: 134, homeRuns: 24, rbi: 81, runs: 76 },
  },

  // SSG 랜더스 (일부만 예시로 추가)
  {
    id: "ssg-cho-byung-hyun",
    name: "조병현",
    number: 19,
    position: "투수",
    team: "SSG",
    teamKorean: "SSG",
    stats: { era: 3.45, wins: 11, losses: 7, strikeouts: 142 },
  },
  {
    id: "ssg-song-young-jin",
    name: "송영진",
    number: 28,
    position: "투수",
    team: "SSG",
    teamKorean: "SSG",
    stats: { era: 4.12, wins: 8, losses: 9, strikeouts: 98 },
  },
  {
    id: "ssg-kim-kwang-hyun",
    name: "김광현",
    number: 29,
    position: "투수",
    team: "SSG",
    teamKorean: "SSG",
    stats: { era: 2.87, wins: 16, losses: 4, strikeouts: 178 },
  },
  {
    id: "ssg-choi-min-jun",
    name: "최민준",
    number: 30,
    position: "투수",
    team: "SSG",
    teamKorean: "SSG",
    stats: { era: 3.78, wins: 10, losses: 6, strikeouts: 125 },
  },
  {
    id: "ssg-anderson",
    name: "앤더슨",
    number: 33,
    position: "투수",
    team: "SSG",
    teamKorean: "SSG",
    stats: { era: 3.21, wins: 13, losses: 5, strikeouts: 165 },
  },

  {
    id: "ssg-cho-hyung-woo",
    name: "조형우",
    number: 20,
    position: "포수",
    team: "SSG",
    teamKorean: "SSG",
    stats: { avg: 0.278, hits: 95, homeRuns: 13, rbi: 52, runs: 44 },
  },
  {
    id: "ssg-lee-yul-ye",
    name: "이율예",
    number: 32,
    position: "포수",
    team: "SSG",
    teamKorean: "SSG",
    stats: { avg: 0.245, hits: 67, homeRuns: 8, rbi: 34, runs: 31 },
  },

  {
    id: "ssg-ahn-sang-hyun",
    name: "안상현",
    number: 10,
    position: "내야수",
    team: "SSG",
    teamKorean: "SSG",
    stats: { avg: 0.289, hits: 123, homeRuns: 19, rbi: 68, runs: 72 },
  },
  {
    id: "ssg-choi-jung",
    name: "최정",
    number: 14,
    position: "내야수",
    team: "SSG",
    teamKorean: "SSG",
    stats: { avg: 0.318, hits: 156, homeRuns: 38, rbi: 108, runs: 89 },
  },
  {
    id: "ssg-ko-myung-jun",
    name: "고명준",
    number: 18,
    position: "내야수",
    team: "SSG",
    teamKorean: "SSG",
    stats: { avg: 0.267, hits: 89, homeRuns: 15, rbi: 56, runs: 61 },
  },
  {
    id: "ssg-park-sung-han",
    name: "박성한",
    number: 2,
    position: "내야수",
    team: "SSG",
    teamKorean: "SSG",
    stats: { avg: 0.234, hits: 56, homeRuns: 9, rbi: 32, runs: 38 },
  },

  {
    id: "ssg-chae-hyun-woo",
    name: "채현우",
    number: 15,
    position: "외야수",
    team: "SSG",
    teamKorean: "SSG",
    stats: { avg: 0.301, hits: 134, homeRuns: 26, rbi: 84, runs: 78 },
  },
  {
    id: "ssg-han-yu-seom",
    name: "한유섬",
    number: 35,
    position: "외야수",
    team: "SSG",
    teamKorean: "SSG",
    stats: { avg: 0.278, hits: 98, homeRuns: 17, rbi: 62, runs: 69 },
  },

  // KT 위즈
  {
    id: "kt-go-young-pyo",
    name: "고영표",
    number: 1,
    position: "투수",
    team: "KT",
    teamKorean: "KT",
    stats: { era: 3.45, wins: 12, losses: 8, strikeouts: 145 },
  },
  {
    id: "kt-woo-kyu-min",
    name: "우규민",
    number: 12,
    position: "투수",
    team: "KT",
    teamKorean: "KT",
    stats: { era: 4.12, wins: 8, losses: 6, strikeouts: 98 },
  },
  {
    id: "kt-choi-dong-hwan",
    name: "최동환",
    number: 16,
    position: "투수",
    team: "KT",
    teamKorean: "KT",
    stats: { era: 3.89, wins: 9, losses: 7, strikeouts: 112 },
  },
  {
    id: "kt-moon-yong-ik",
    name: "문용익",
    number: 18,
    position: "투수",
    team: "KT",
    teamKorean: "KT",
    stats: { era: 2.98, wins: 15, losses: 4, strikeouts: 167 },
  },
  {
    id: "kt-kim-min-soo",
    name: "김민수",
    number: 26,
    position: "투수",
    team: "KT",
    teamKorean: "KT",
    stats: { era: 4.56, wins: 6, losses: 9, strikeouts: 87 },
  },
  {
    id: "kt-so-hyung-jun",
    name: "소형준",
    number: 30,
    position: "투수",
    team: "KT",
    teamKorean: "KT",
    stats: { era: 3.67, wins: 10, losses: 5, strikeouts: 134 },
  },
  {
    id: "kt-patrick",
    name: "패트릭",
    number: 32,
    position: "투수",
    team: "KT",
    teamKorean: "KT",
    stats: { era: 3.21, wins: 11, losses: 6, strikeouts: 156 },
  },
  {
    id: "kt-lee-sang-dong",
    name: "이상동",
    number: 37,
    position: "투수",
    team: "KT",
    teamKorean: "KT",
    stats: { era: 4.23, wins: 7, losses: 8, strikeouts: 92 },
  },
  {
    id: "kt-ju-kwon",
    name: "주권",
    number: 38,
    position: "투수",
    team: "KT",
    teamKorean: "KT",
    stats: { era: 3.78, wins: 8, losses: 7, strikeouts: 105 },
  },
  {
    id: "kt-son-dong-hyun",
    name: "손동현",
    number: 41,
    position: "투수",
    team: "KT",
    teamKorean: "KT",
    stats: { era: 4.01, wins: 9, losses: 6, strikeouts: 118 },
  },
  {
    id: "kt-park-gun-woo",
    name: "박건우",
    number: 46,
    position: "투수",
    team: "KT",
    teamKorean: "KT",
    stats: { era: 3.54, wins: 12, losses: 7, strikeouts: 142 },
  },
  {
    id: "kt-oh-won-seok",
    name: "오원석",
    number: 47,
    position: "투수",
    team: "KT",
    teamKorean: "KT",
    stats: { era: 4.34, wins: 5, losses: 10, strikeouts: 78 },
  },
  {
    id: "kt-park-young-hyun",
    name: "박영현",
    number: 60,
    position: "투수",
    team: "KT",
    teamKorean: "KT",
    stats: { era: 3.92, wins: 8, losses: 8, strikeouts: 101 },
  },
  {
    id: "kt-won-sang-hyun",
    name: "원상현",
    number: 63,
    position: "투수",
    team: "KT",
    teamKorean: "KT",
    stats: { era: 2.87, wins: 14, losses: 5, strikeouts: 178 },
  },
  {
    id: "kt-heysuess",
    name: "헤이수스",
    number: 65,
    position: "투수",
    team: "KT",
    teamKorean: "KT",
    stats: { era: 4.67, wins: 4, losses: 11, strikeouts: 65 },
  },

  {
    id: "kt-jang-sung-woo",
    name: "장성우",
    number: 22,
    position: "포수",
    team: "KT",
    teamKorean: "KT",
    stats: { avg: 0.267, hits: 89, homeRuns: 12, rbi: 45, runs: 38 },
  },
  {
    id: "kt-jo-dae-hyun",
    name: "조대현",
    number: 42,
    position: "포수",
    team: "KT",
    teamKorean: "KT",
    stats: { avg: 0.245, hits: 67, homeRuns: 8, rbi: 32, runs: 28 },
  },
  {
    id: "kt-kang-baek-ho",
    name: "강백호",
    number: 50,
    position: "포수",
    team: "KT",
    teamKorean: "KT",
    stats: { avg: 0.289, hits: 95, homeRuns: 15, rbi: 52, runs: 41 },
  },
  {
    id: "kt-kang-hyun-woo",
    name: "강현우",
    number: 55,
    position: "포수",
    team: "KT",
    teamKorean: "KT",
    stats: { avg: 0.278, hits: 78, homeRuns: 9, rbi: 34, runs: 32 },
  },

  {
    id: "kt-hwang-jae-gyun",
    name: "황재균",
    number: 10,
    position: "내야수",
    team: "KT",
    teamKorean: "KT",
    stats: { avg: 0.312, hits: 145, homeRuns: 28, rbi: 89, runs: 78 },
  },
  {
    id: "kt-heo-kyung-min",
    name: "허경민",
    number: 13,
    position: "내야수",
    team: "KT",
    teamKorean: "KT",
    stats: { avg: 0.278, hits: 98, homeRuns: 18, rbi: 56, runs: 52 },
  },
  {
    id: "kt-moon-sang-chul",
    name: "문상철",
    number: 24,
    position: "내야수",
    team: "KT",
    teamKorean: "KT",
    stats: { avg: 0.295, hits: 132, homeRuns: 35, rbi: 98, runs: 67 },
  },
  {
    id: "kt-oh-seo-jin",
    name: "오서진",
    number: 25,
    position: "내야수",
    team: "KT",
    teamKorean: "KT",
    stats: { avg: 0.256, hits: 76, homeRuns: 9, rbi: 34, runs: 41 },
  },
  {
    id: "kt-lee-ho-yeon",
    name: "이호연",
    number: 34,
    position: "내야수",
    team: "KT",
    teamKorean: "KT",
    stats: { avg: 0.234, hits: 54, homeRuns: 6, rbi: 28, runs: 32 },
  },
  {
    id: "kt-kwon-dong-jin",
    name: "권동진",
    number: 52,
    position: "내야수",
    team: "KT",
    teamKorean: "KT",
    stats: { avg: 0.289, hits: 112, homeRuns: 14, rbi: 67, runs: 58 },
  },
  {
    id: "kt-jang-jun-won",
    name: "장준원",
    number: 56,
    position: "내야수",
    team: "KT",
    teamKorean: "KT",
    stats: { avg: 0.267, hits: 89, homeRuns: 11, rbi: 43, runs: 49 },
  },
  {
    id: "kt-kim-sang-soo",
    name: "김상수",
    number: 7,
    position: "내야수",
    team: "KT",
    teamKorean: "KT",
    stats: { avg: 0.245, hits: 67, homeRuns: 8, rbi: 29, runs: 35 },
  },

  {
    id: "kt-ahn-hyun-min",
    name: "안현민",
    number: 23,
    position: "외야수",
    team: "KT",
    teamKorean: "KT",
    stats: { avg: 0.301, hits: 134, homeRuns: 22, rbi: 71, runs: 82 },
  },
  {
    id: "kt-stevenson",
    name: "스티븐슨",
    number: 3,
    position: "외야수",
    team: "KT",
    teamKorean: "KT",
    stats: { avg: 0.318, hits: 156, homeRuns: 31, rbi: 95, runs: 89 },
  },
  {
    id: "kt-lee-jung-hoon",
    name: "이정훈",
    number: 33,
    position: "외야수",
    team: "KT",
    teamKorean: "KT",
    stats: { avg: 0.278, hits: 98, homeRuns: 15, rbi: 54, runs: 61 },
  },
  {
    id: "kt-jang-jin-hyuk",
    name: "장진혁",
    number: 51,
    position: "외야수",
    team: "KT",
    teamKorean: "KT",
    stats: { avg: 0.234, hits: 56, homeRuns: 7, rbi: 26, runs: 31 },
  },
  {
    id: "kt-yu-jun-gyu",
    name: "유준규",
    number: 67,
    position: "외야수",
    team: "KT",
    teamKorean: "KT",
    stats: { avg: 0.289, hits: 123, homeRuns: 19, rbi: 68, runs: 74 },
  },
  {
    id: "kt-ahn-chi-young",
    name: "안치영",
    number: 8,
    position: "외야수",
    team: "KT",
    teamKorean: "KT",
    stats: { avg: 0.256, hits: 78, homeRuns: 12, rbi: 41, runs: 45 },
  },

  // 삼성 라이온즈
  {
    id: "sam-lee-ho-sung",
    name: "이호성",
    number: 1,
    position: "투수",
    team: "SAM",
    teamKorean: "삼성",
    stats: { era: 3.21, wins: 13, losses: 7, strikeouts: 158 },
  },
  {
    id: "sam-won-tae-in",
    name: "원태인",
    number: 18,
    position: "투수",
    team: "SAM",
    teamKorean: "삼성",
    stats: { era: 4.12, wins: 8, losses: 9, strikeouts: 102 },
  },
  {
    id: "sam-yang-hyun",
    name: "양현",
    number: 19,
    position: "투수",
    team: "SAM",
    teamKorean: "삼성",
    stats: { era: 3.78, wins: 10, losses: 6, strikeouts: 134 },
  },
  {
    id: "sam-lee-seung-hyun",
    name: "이승현",
    number: 20,
    position: "투수",
    team: "SAM",
    teamKorean: "삼성",
    stats: { era: 2.95, wins: 15, losses: 4, strikeouts: 172 },
  },
  {
    id: "sam-lee-jae-ik",
    name: "이재익",
    number: 26,
    position: "투수",
    team: "SAM",
    teamKorean: "삼성",
    stats: { era: 4.45, wins: 6, losses: 10, strikeouts: 89 },
  },
  {
    id: "sam-kim-tae-hoon",
    name: "김태훈",
    number: 27,
    position: "투수",
    team: "SAM",
    teamKorean: "삼성",
    stats: { era: 3.67, wins: 9, losses: 7, strikeouts: 118 },
  },
  {
    id: "sam-lee-seung-min",
    name: "이승민",
    number: 28,
    position: "투수",
    team: "SAM",
    teamKorean: "삼성",
    stats: { era: 4.01, wins: 7, losses: 8, strikeouts: 95 },
  },
  {
    id: "sam-choi-won-tae",
    name: "최원태",
    number: 3,
    position: "투수",
    team: "SAM",
    teamKorean: "삼성",
    stats: { era: 3.54, wins: 11, losses: 5, strikeouts: 142 },
  },
  {
    id: "sam-yuk-sun-yeop",
    name: "육선엽",
    number: 4,
    position: "투수",
    team: "SAM",
    teamKorean: "삼성",
    stats: { era: 4.23, wins: 5, losses: 11, strikeouts: 76 },
  },
  {
    id: "sam-yang-chang-seop",
    name: "양창섭",
    number: 42,
    position: "투수",
    team: "SAM",
    teamKorean: "삼성",
    stats: { era: 3.89, wins: 8, losses: 7, strikeouts: 108 },
  },
  {
    id: "sam-bae-chan-seung",
    name: "배찬승",
    number: 55,
    position: "투수",
    team: "SAM",
    teamKorean: "삼성",
    stats: { era: 3.12, wins: 12, losses: 6, strikeouts: 165 },
  },
  {
    id: "sam-lee-seung-hyun-57",
    name: "이승현",
    number: 57,
    position: "투수",
    team: "SAM",
    teamKorean: "삼성",
    stats: { era: 4.56, wins: 4, losses: 12, strikeouts: 67 },
  },
  {
    id: "sam-garabito",
    name: "가라비토",
    number: 60,
    position: "투수",
    team: "SAM",
    teamKorean: "삼성",
    stats: { era: 3.78, wins: 9, losses: 8, strikeouts: 125 },
  },
  {
    id: "sam-hwang-dong-jae",
    name: "황동재",
    number: 61,
    position: "투수",
    team: "SAM",
    teamKorean: "삼성",
    stats: { era: 4.34, wins: 6, losses: 9, strikeouts: 82 },
  },
  {
    id: "sam-kim-jae-yoon",
    name: "김재윤",
    number: 62,
    position: "투수",
    team: "SAM",
    teamKorean: "삼성",
    stats: { era: 2.76, wins: 18, losses: 3, strikeouts: 189 },
  },

  {
    id: "sam-kim-jae-sung",
    name: "김재성",
    number: 2,
    position: "포수",
    team: "SAM",
    teamKorean: "삼성",
    stats: { avg: 0.278, hits: 95, homeRuns: 14, rbi: 48, runs: 42 },
  },
  {
    id: "sam-lee-byung-hun",
    name: "이병헌",
    number: 23,
    position: "포수",
    team: "SAM",
    teamKorean: "삼성",
    stats: { avg: 0.245, hits: 67, homeRuns: 9, rbi: 35, runs: 29 },
  },
  {
    id: "sam-kang-min-ho",
    name: "강민호",
    number: 47,
    position: "포수",
    team: "SAM",
    teamKorean: "삼성",
    stats: { avg: 0.289, hits: 112, homeRuns: 16, rbi: 58, runs: 51 },
  },

  {
    id: "sam-diaz",
    name: "디아즈",
    number: 0,
    position: "내야수",
    team: "SAM",
    teamKorean: "삼성",
    stats: { avg: 0.301, hits: 134, homeRuns: 25, rbi: 78, runs: 69 },
  },
  {
    id: "sam-ryu-ji-hyuk",
    name: "류지혁",
    number: 16,
    position: "내야수",
    team: "SAM",
    teamKorean: "삼성",
    stats: { avg: 0.267, hits: 89, homeRuns: 12, rbi: 45, runs: 52 },
  },
  {
    id: "sam-kim-young-woong",
    name: "김영웅",
    number: 30,
    position: "내야수",
    team: "SAM",
    teamKorean: "삼성",
    stats: { avg: 0.289, hits: 123, homeRuns: 18, rbi: 67, runs: 74 },
  },
  {
    id: "sam-jeon-byung-woo",
    name: "전병우",
    number: 34,
    position: "내야수",
    team: "SAM",
    teamKorean: "삼성",
    stats: { avg: 0.312, hits: 145, homeRuns: 32, rbi: 95, runs: 82 },
  },
  {
    id: "sam-cha-seung-jun",
    name: "차승준",
    number: 35,
    position: "내야수",
    team: "SAM",
    teamKorean: "삼성",
    stats: { avg: 0.234, hits: 56, homeRuns: 7, rbi: 28, runs: 35 },
  },
  {
    id: "sam-lee-hae-seung",
    name: "이해승",
    number: 56,
    position: "내야수",
    team: "SAM",
    teamKorean: "삼성",
    stats: { avg: 0.278, hits: 98, homeRuns: 15, rbi: 54, runs: 61 },
  },
  {
    id: "sam-yang-do-geun",
    name: "양도근",
    number: 68,
    position: "내야수",
    team: "SAM",
    teamKorean: "삼성",
    stats: { avg: 0.295, hits: 132, homeRuns: 29, rbi: 89, runs: 76 },
  },
  {
    id: "sam-lee-jae-hyun",
    name: "이재현",
    number: 7,
    position: "내야수",
    team: "SAM",
    teamKorean: "삼성",
    stats: { avg: 0.245, hits: 67, homeRuns: 8, rbi: 32, runs: 38 },
  },

  {
    id: "sam-lee-sung-gyu",
    name: "이성규",
    number: 13,
    position: "외야수",
    team: "SAM",
    teamKorean: "삼성",
    stats: { avg: 0.318, hits: 156, homeRuns: 35, rbi: 102, runs: 89 },
  },
  {
    id: "sam-kim-tae-hoon-25",
    name: "김태훈",
    number: 25,
    position: "외야수",
    team: "SAM",
    teamKorean: "삼성",
    stats: { avg: 0.267, hits: 89, homeRuns: 14, rbi: 48, runs: 55 },
  },
  {
    id: "sam-kim-hun-gon",
    name: "김헌곤",
    number: 32,
    position: "외야수",
    team: "SAM",
    teamKorean: "삼성",
    stats: { avg: 0.289, hits: 123, homeRuns: 21, rbi: 72, runs: 68 },
  },
  {
    id: "sam-kim-sung-yoon",
    name: "김성윤",
    number: 39,
    position: "외야수",
    team: "SAM",
    teamKorean: "삼성",
    stats: { avg: 0.234, hits: 56, homeRuns: 9, rbi: 31, runs: 42 },
  },
  {
    id: "sam-koo-ja-wook",
    name: "구자욱",
    number: 5,
    position: "외야수",
    team: "SAM",
    teamKorean: "삼성",
    stats: { avg: 0.278, hits: 98, homeRuns: 16, rbi: 58, runs: 64 },
  },
  {
    id: "sam-kim-ji-chan",
    name: "김지찬",
    number: 58,
    position: "외야수",
    team: "SAM",
    teamKorean: "삼성",
    stats: { avg: 0.256, hits: 78, homeRuns: 11, rbi: 41, runs: 49 },
  },
  {
    id: "sam-hong-hyun-bin",
    name: "홍현빈",
    number: 63,
    position: "외야수",
    team: "SAM",
    teamKorean: "삼성",
    stats: { avg: 0.301, hits: 134, homeRuns: 24, rbi: 81, runs: 76 },
  },

  // 롯데 자이언츠
  {
    id: "lot-jung-sung-jong",
    name: "정성종",
    number: 18,
    position: "투수",
    team: "LOT",
    teamKorean: "롯데",
    stats: { era: 3.45, wins: 11, losses: 7, strikeouts: 142 },
  },
  {
    id: "lot-kim-kang-hyun",
    name: "김강현",
    number: 19,
    position: "투수",
    team: "LOT",
    teamKorean: "롯데",
    stats: { era: 4.12, wins: 8, losses: 9, strikeouts: 98 },
  },
  {
    id: "lot-park-se-woong",
    name: "박세웅",
    number: 21,
    position: "투수",
    team: "LOT",
    teamKorean: "롯데",
    stats: { era: 2.87, wins: 16, losses: 4, strikeouts: 178 },
  },
  {
    id: "lot-velasquez",
    name: "벨라스케즈",
    number: 26,
    position: "투수",
    team: "LOT",
    teamKorean: "롯데",
    stats: { era: 3.78, wins: 10, losses: 6, strikeouts: 125 },
  },
  {
    id: "lot-gamboa",
    name: "감보아",
    number: 32,
    position: "투수",
    team: "LOT",
    teamKorean: "롯데",
    stats: { era: 3.21, wins: 13, losses: 5, strikeouts: 165 },
  },
  {
    id: "lot-kim-won-joong",
    name: "김원중",
    number: 34,
    position: "투수",
    team: "LOT",
    teamKorean: "롯데",
    stats: { era: 4.45, wins: 6, losses: 10, strikeouts: 89 },
  },
  {
    id: "lot-lee-min-seok",
    name: "이민석",
    number: 37,
    position: "투수",
    team: "LOT",
    teamKorean: "롯데",
    stats: { era: 3.67, wins: 9, losses: 7, strikeouts: 118 },
  },
  {
    id: "lot-park-jin-hyung",
    name: "박진형",
    number: 40,
    position: "투수",
    team: "LOT",
    teamKorean: "롯데",
    stats: { era: 4.01, wins: 7, losses: 8, strikeouts: 95 },
  },
  {
    id: "lot-na-gyun-an",
    name: "나균안",
    number: 43,
    position: "투수",
    team: "LOT",
    teamKorean: "롯데",
    stats: { era: 3.54, wins: 11, losses: 5, strikeouts: 142 },
  },
  {
    id: "lot-park-jin",
    name: "박진",
    number: 44,
    position: "투수",
    team: "LOT",
    teamKorean: "롯데",
    stats: { era: 4.23, wins: 5, losses: 11, strikeouts: 76 },
  },
  {
    id: "lot-yoon-sung-bin",
    name: "윤성빈",
    number: 55,
    position: "투수",
    team: "LOT",
    teamKorean: "롯데",
    stats: { era: 3.89, wins: 8, losses: 7, strikeouts: 108 },
  },
  {
    id: "lot-choi-jun-yong",
    name: "최준용",
    number: 56,
    position: "투수",
    team: "LOT",
    teamKorean: "롯데",
    stats: { era: 3.12, wins: 12, losses: 6, strikeouts: 165 },
  },
  {
    id: "lot-jung-hyun-soo",
    name: "정현수",
    number: 57,
    position: "투수",
    team: "LOT",
    teamKorean: "롯데",
    stats: { era: 4.56, wins: 4, losses: 12, strikeouts: 67 },
  },
  {
    id: "lot-jung-chul-won",
    name: "정철원",
    number: 65,
    position: "투수",
    team: "LOT",
    teamKorean: "롯데",
    stats: { era: 3.78, wins: 9, losses: 8, strikeouts: 125 },
  },

  {
    id: "lot-yu-kang-nam",
    name: "유강남",
    number: 27,
    position: "포수",
    team: "LOT",
    teamKorean: "롯데",
    stats: { avg: 0.278, hits: 95, homeRuns: 13, rbi: 52, runs: 44 },
  },
  {
    id: "lot-son-sung-bin",
    name: "손성빈",
    number: 28,
    position: "포수",
    team: "LOT",
    teamKorean: "롯데",
    stats: { avg: 0.245, hits: 67, homeRuns: 8, rbi: 34, runs: 31 },
  },
  {
    id: "lot-jung-bo-geun",
    name: "정보근",
    number: 42,
    position: "포수",
    team: "LOT",
    teamKorean: "롯데",
    stats: { avg: 0.289, hits: 123, homeRuns: 19, rbi: 68, runs: 72 },
  },
  {
    id: "lot-park-gun-woo",
    name: "박건우",
    number: 48,
    position: "포수",
    team: "LOT",
    teamKorean: "롯데",
    stats: { avg: 0.267, hits: 89, homeRuns: 15, rbi: 56, runs: 61 },
  },

  {
    id: "lot-jeon-min-jae",
    name: "전민재",
    number: 13,
    position: "내야수",
    team: "LOT",
    teamKorean: "롯데",
    stats: { avg: 0.318, hits: 156, homeRuns: 38, rbi: 108, runs: 89 },
  },
  {
    id: "lot-kim-min-sung",
    name: "김민성",
    number: 16,
    position: "내야수",
    team: "LOT",
    teamKorean: "롯데",
    stats: { avg: 0.234, hits: 56, homeRuns: 9, rbi: 32, runs: 38 },
  },
  {
    id: "lot-go-seung-min",
    name: "고승민",
    number: 2,
    position: "내야수",
    team: "LOT",
    teamKorean: "롯데",
    stats: { avg: 0.301, hits: 134, homeRuns: 26, rbi: 84, runs: 78 },
  },
  {
    id: "lot-lee-ho-jun",
    name: "이호준",
    number: 30,
    position: "내야수",
    team: "LOT",
    teamKorean: "롯데",
    stats: { avg: 0.278, hits: 98, homeRuns: 17, rbi: 62, runs: 69 },
  },
  {
    id: "lot-son-ho-young",
    name: "손호영",
    number: 33,
    position: "내야수",
    team: "LOT",
    teamKorean: "롯데",
    stats: { avg: 0.267, hits: 89, homeRuns: 12, rbi: 45, runs: 52 },
  },
  {
    id: "lot-na-seung-yeop",
    name: "나승엽",
    number: 51,
    position: "내야수",
    team: "LOT",
    teamKorean: "롯데",
    stats: { avg: 0.289, hits: 123, homeRuns: 18, rbi: 67, runs: 74 },
  },
  {
    id: "lot-han-tae-yang",
    name: "한태양",
    number: 6,
    position: "내야수",
    team: "LOT",
    teamKorean: "롯데",
    stats: { avg: 0.312, hits: 145, homeRuns: 32, rbi: 95, runs: 82 },
  },
  {
    id: "lot-park-chan-hyung",
    name: "박찬형",
    number: 60,
    position: "내야수",
    team: "LOT",
    teamKorean: "롯데",
    stats: { avg: 0.234, hits: 56, homeRuns: 7, rbi: 28, runs: 35 },
  },
  {
    id: "lot-jung-hoon",
    name: "정훈",
    number: 9,
    position: "내야수",
    team: "LOT",
    teamKorean: "롯데",
    stats: { avg: 0.278, hits: 98, homeRuns: 15, rbi: 54, runs: 61 },
  },

  {
    id: "lot-hwang-sung-bin",
    name: "황성빈",
    number: 0,
    position: "외야수",
    team: "LOT",
    teamKorean: "롯데",
    stats: { avg: 0.318, hits: 156, homeRuns: 35, rbi: 102, runs: 89 },
  },
  {
    id: "lot-reyes",
    name: "레이예스",
    number: 29,
    position: "외야수",
    team: "LOT",
    teamKorean: "롯데",
    stats: { avg: 0.267, hits: 89, homeRuns: 14, rbi: 48, runs: 55 },
  },
  {
    id: "lot-jo-se-jin",
    name: "조세진",
    number: 5,
    position: "외야수",
    team: "LOT",
    teamKorean: "롯데",
    stats: { avg: 0.289, hits: 123, homeRuns: 21, rbi: 72, runs: 68 },
  },
  {
    id: "lot-kim-dong-hyuk",
    name: "김동혁",
    number: 50,
    position: "외야수",
    team: "LOT",
    teamKorean: "롯데",
    stats: { avg: 0.234, hits: 56, homeRuns: 9, rbi: 31, runs: 42 },
  },
  {
    id: "lot-jang-doo-sung",
    name: "장두성",
    number: 7,
    position: "외야수",
    team: "LOT",
    teamKorean: "롯데",
    stats: { avg: 0.278, hits: 98, homeRuns: 16, rbi: 58, runs: 64 },
  },
  {
    id: "lot-yoon-dong-hee",
    name: "윤동희",
    number: 91,
    position: "외야수",
    team: "LOT",
    teamKorean: "롯데",
    stats: { avg: 0.256, hits: 78, homeRuns: 11, rbi: 41, runs: 49 },
  },

  // NC 다이노스
  {
    id: "nc-logan",
    name: "로건",
    number: 12,
    position: "투수",
    team: "NC",
    teamKorean: "NC",
    stats: { era: 3.45, wins: 11, losses: 7, strikeouts: 142 },
  },
  {
    id: "nc-kim-young-gyu",
    name: "김영규",
    number: 17,
    position: "투수",
    team: "NC",
    teamKorean: "NC",
    stats: { era: 4.12, wins: 8, losses: 9, strikeouts: 98 },
  },
  {
    id: "nc-shin-min-hyuk",
    name: "신민혁",
    number: 18,
    position: "투수",
    team: "NC",
    teamKorean: "NC",
    stats: { era: 2.87, wins: 16, losses: 4, strikeouts: 178 },
  },
  {
    id: "nc-lim-ji-min",
    name: "임지민",
    number: 19,
    position: "투수",
    team: "NC",
    teamKorean: "NC",
    stats: { era: 3.78, wins: 10, losses: 6, strikeouts: 125 },
  },
  {
    id: "nc-kim-nok-won",
    name: "김녹원",
    number: 22,
    position: "투수",
    team: "NC",
    teamKorean: "NC",
    stats: { era: 3.21, wins: 13, losses: 5, strikeouts: 165 },
  },
  {
    id: "nc-choi-sung-young",
    name: "최성영",
    number: 26,
    position: "투수",
    team: "NC",
    teamKorean: "NC",
    stats: { era: 4.45, wins: 6, losses: 10, strikeouts: 89 },
  },
  {
    id: "nc-ha-jun-young",
    name: "하준영",
    number: 29,
    position: "투수",
    team: "NC",
    teamKorean: "NC",
    stats: { era: 3.67, wins: 9, losses: 7, strikeouts: 118 },
  },
  {
    id: "nc-riley",
    name: "라일리",
    number: 3,
    position: "투수",
    team: "NC",
    teamKorean: "NC",
    stats: { era: 4.01, wins: 7, losses: 8, strikeouts: 95 },
  },
  {
    id: "nc-shin-young-woo",
    name: "신영우",
    number: 43,
    position: "투수",
    team: "NC",
    teamKorean: "NC",
    stats: { era: 3.54, wins: 11, losses: 5, strikeouts: 142 },
  },
  {
    id: "nc-lee-yong-chan",
    name: "이용찬",
    number: 45,
    position: "투수",
    team: "NC",
    teamKorean: "NC",
    stats: { era: 4.23, wins: 5, losses: 11, strikeouts: 76 },
  },
  {
    id: "nc-son-ju-hwan",
    name: "손주환",
    number: 46,
    position: "투수",
    team: "NC",
    teamKorean: "NC",
    stats: { era: 3.89, wins: 8, losses: 7, strikeouts: 108 },
  },
  {
    id: "nc-choi-woo-seok",
    name: "최우석",
    number: 48,
    position: "투수",
    team: "NC",
    teamKorean: "NC",
    stats: { era: 3.12, wins: 12, losses: 6, strikeouts: 165 },
  },
  {
    id: "nc-kim-jin-ho",
    name: "김진호",
    number: 54,
    position: "투수",
    team: "NC",
    teamKorean: "NC",
    stats: { era: 4.56, wins: 4, losses: 12, strikeouts: 67 },
  },
  {
    id: "nc-jeon-sa-min",
    name: "전사민",
    number: 57,
    position: "투수",
    team: "NC",
    teamKorean: "NC",
    stats: { era: 3.78, wins: 9, losses: 8, strikeouts: 125 },
  },
  {
    id: "nc-gu-chang-mo",
    name: "구창모",
    number: 59,
    position: "투수",
    team: "NC",
    teamKorean: "NC",
    stats: { era: 4.34, wins: 6, losses: 9, strikeouts: 82 },
  },
  {
    id: "nc-bae-jae-hwan",
    name: "배재환",
    number: 61,
    position: "투수",
    team: "NC",
    teamKorean: "NC",
    stats: { era: 2.76, wins: 18, losses: 3, strikeouts: 189 },
  },

  {
    id: "nc-ahn-jung-yeol",
    name: "안중열",
    number: 1,
    position: "포수",
    team: "NC",
    teamKorean: "NC",
    stats: { avg: 0.278, hits: 95, homeRuns: 13, rbi: 52, runs: 44 },
  },
  {
    id: "nc-park-se-hyuk",
    name: "박세혁",
    number: 10,
    position: "포수",
    team: "NC",
    teamKorean: "NC",
    stats: { avg: 0.245, hits: 67, homeRuns: 8, rbi: 34, runs: 31 },
  },
  {
    id: "nc-kim-hyung-jun",
    name: "김형준",
    number: 25,
    position: "포수",
    team: "NC",
    teamKorean: "NC",
    stats: { avg: 0.289, hits: 123, homeRuns: 19, rbi: 68, runs: 72 },
  },

  {
    id: "nc-choi-jung-won",
    name: "최정원",
    number: 14,
    position: "내야수",
    team: "NC",
    teamKorean: "NC",
    stats: { avg: 0.318, hits: 156, homeRuns: 38, rbi: 108, runs: 89 },
  },
  {
    id: "nc-do-tae-hoon",
    name: "도태훈",
    number: 16,
    position: "내야수",
    team: "NC",
    teamKorean: "NC",
    stats: { avg: 0.234, hits: 56, homeRuns: 9, rbi: 32, runs: 38 },
  },
  {
    id: "nc-park-min-woo",
    name: "박민우",
    number: 2,
    position: "내야수",
    team: "NC",
    teamKorean: "NC",
    stats: { avg: 0.301, hits: 134, homeRuns: 26, rbi: 84, runs: 78 },
  },
  {
    id: "nc-davidson",
    name: "데이비슨",
    number: 24,
    position: "내야수",
    team: "NC",
    teamKorean: "NC",
    stats: { avg: 0.278, hits: 98, homeRuns: 17, rbi: 62, runs: 69 },
  },
  {
    id: "nc-oh-young-soo",
    name: "오영수",
    number: 34,
    position: "내야수",
    team: "NC",
    teamKorean: "NC",
    stats: { avg: 0.267, hits: 89, homeRuns: 12, rbi: 45, runs: 52 },
  },
  {
    id: "nc-kim-hwi-jip",
    name: "김휘집",
    number: 44,
    position: "내야수",
    team: "NC",
    teamKorean: "NC",
    stats: { avg: 0.289, hits: 123, homeRuns: 18, rbi: 67, runs: 74 },
  },
  {
    id: "nc-seo-ho-chul",
    name: "서호철",
    number: 5,
    position: "내야수",
    team: "NC",
    teamKorean: "NC",
    stats: { avg: 0.312, hits: 145, homeRuns: 32, rbi: 95, runs: 82 },
  },
  {
    id: "nc-kim-han-byul",
    name: "김한별",
    number: 68,
    position: "내야수",
    team: "NC",
    teamKorean: "NC",
    stats: { avg: 0.234, hits: 56, homeRuns: 7, rbi: 28, runs: 35 },
  },
  {
    id: "nc-kim-ju-won",
    name: "김주원",
    number: 7,
    position: "내야수",
    team: "NC",
    teamKorean: "NC",
    stats: { avg: 0.278, hits: 98, homeRuns: 15, rbi: 54, runs: 61 },
  },

  {
    id: "nc-cheon-jae-hwan",
    name: "천재환",
    number: 23,
    position: "외야수",
    team: "NC",
    teamKorean: "NC",
    stats: { avg: 0.318, hits: 156, homeRuns: 35, rbi: 102, runs: 89 },
  },
  {
    id: "nc-choi-won-jun",
    name: "최원준",
    number: 31,
    position: "외야수",
    team: "NC",
    teamKorean: "NC",
    stats: { avg: 0.267, hits: 89, homeRuns: 14, rbi: 48, runs: 55 },
  },
  {
    id: "nc-kwon-hee-dong",
    name: "권희동",
    number: 36,
    position: "외야수",
    team: "NC",
    teamKorean: "NC",
    stats: { avg: 0.289, hits: 123, homeRuns: 21, rbi: 72, runs: 68 },
  },
  {
    id: "nc-park-gun-woo-37",
    name: "박건우",
    number: 37,
    position: "외야수",
    team: "NC",
    teamKorean: "NC",
    stats: { avg: 0.234, hits: 56, homeRuns: 9, rbi: 31, runs: 42 },
  },
  {
    id: "nc-lee-woo-sung",
    name: "이우성",
    number: 55,
    position: "외야수",
    team: "NC",
    teamKorean: "NC",
    stats: { avg: 0.278, hits: 98, homeRuns: 16, rbi: 58, runs: 64 },
  },

  // KIA 타이거즈
  {
    id: "kia-kim-tae-hyung",
    name: "김태형",
    number: 10,
    position: "투수",
    team: "KIA",
    teamKorean: "KIA",
    stats: { era: 3.45, wins: 11, losses: 7, strikeouts: 142 },
  },
  {
    id: "kia-jo-sang-woo",
    name: "조상우",
    number: 11,
    position: "투수",
    team: "KIA",
    teamKorean: "KIA",
    stats: { era: 4.12, wins: 8, losses: 9, strikeouts: 98 },
  },
  {
    id: "kia-lee-jun-young",
    name: "이준영",
    number: 20,
    position: "투수",
    team: "KIA",
    teamKorean: "KIA",
    stats: { era: 2.87, wins: 16, losses: 4, strikeouts: 178 },
  },
  {
    id: "kia-han-jae-seung",
    name: "한재승",
    number: 25,
    position: "투수",
    team: "KIA",
    teamKorean: "KIA",
    stats: { era: 3.78, wins: 10, losses: 6, strikeouts: 125 },
  },
  {
    id: "kia-oller",
    name: "올러",
    number: 33,
    position: "투수",
    team: "KIA",
    teamKorean: "KIA",
    stats: { era: 3.21, wins: 13, losses: 5, strikeouts: 165 },
  },
  {
    id: "kia-choi-ji-min",
    name: "최지민",
    number: 39,
    position: "투수",
    team: "KIA",
    teamKorean: "KIA",
    stats: { era: 4.45, wins: 6, losses: 10, strikeouts: 89 },
  },
  {
    id: "kia-nail",
    name: "네일",
    number: 40,
    position: "투수",
    team: "KIA",
    teamKorean: "KIA",
    stats: { era: 3.67, wins: 9, losses: 7, strikeouts: 118 },
  },
  {
    id: "kia-lee-eui-ri",
    name: "이의리",
    number: 48,
    position: "투수",
    team: "KIA",
    teamKorean: "KIA",
    stats: { era: 4.01, wins: 7, losses: 8, strikeouts: 95 },
  },
  {
    id: "kia-jeon-sang-hyun",
    name: "전상현",
    number: 51,
    position: "투수",
    team: "KIA",
    teamKorean: "KIA",
    stats: { era: 3.54, wins: 11, losses: 5, strikeouts: 142 },
  },
  {
    id: "kia-kim-gi-hoon",
    name: "김기훈",
    number: 53,
    position: "투수",
    team: "KIA",
    teamKorean: "KIA",
    stats: { era: 4.23, wins: 5, losses: 11, strikeouts: 76 },
  },
  {
    id: "kia-yang-hyun-jong",
    name: "양현종",
    number: 54,
    position: "투수",
    team: "KIA",
    teamKorean: "KIA",
    stats: { era: 3.89, wins: 8, losses: 7, strikeouts: 108 },
  },
  {
    id: "kia-lee-sung-won",
    name: "이성원",
    number: 6,
    position: "투수",
    team: "KIA",
    teamKorean: "KIA",
    stats: { era: 3.12, wins: 12, losses: 6, strikeouts: 165 },
  },
  {
    id: "kia-kim-do-hyun",
    name: "김도현",
    number: 60,
    position: "투수",
    team: "KIA",
    teamKorean: "KIA",
    stats: { era: 4.56, wins: 4, losses: 12, strikeouts: 67 },
  },
  {
    id: "kia-jung-hae-young",
    name: "정해영",
    number: 62,
    position: "투수",
    team: "KIA",
    teamKorean: "KIA",
    stats: { era: 3.78, wins: 9, losses: 8, strikeouts: 125 },
  },
  {
    id: "kia-lee-ho-min",
    name: "이호민",
    number: 63,
    position: "투수",
    team: "KIA",
    teamKorean: "KIA",
    stats: { era: 4.34, wins: 6, losses: 9, strikeouts: 82 },
  },
  {
    id: "kia-sung-young-tak",
    name: "성영탁",
    number: 65,
    position: "투수",
    team: "KIA",
    teamKorean: "KIA",
    stats: { era: 2.76, wins: 18, losses: 3, strikeouts: 189 },
  },
  {
    id: "kia-lee-do-hyun",
    name: "이도현",
    number: 66,
    position: "투수",
    team: "KIA",
    teamKorean: "KIA",
    stats: { era: 3.45, wins: 10, losses: 6, strikeouts: 125 },
  },

  {
    id: "kia-han-seung-taek",
    name: "한승택",
    number: 26,
    position: "포수",
    team: "KIA",
    teamKorean: "KIA",
    stats: { avg: 0.278, hits: 95, homeRuns: 13, rbi: 52, runs: 44 },
  },
  {
    id: "kia-kim-tae-gun",
    name: "김태군",
    number: 42,
    position: "포수",
    team: "KIA",
    teamKorean: "KIA",
    stats: { avg: 0.245, hits: 67, homeRuns: 8, rbi: 34, runs: 31 },
  },
  {
    id: "kia-han-jun-soo",
    name: "한준수",
    number: 55,
    position: "포수",
    team: "KIA",
    teamKorean: "KIA",
    stats: { avg: 0.289, hits: 123, homeRuns: 19, rbi: 68, runs: 72 },
  },

  {
    id: "kia-park-chan-ho",
    name: "박찬호",
    number: 1,
    position: "내야수",
    team: "KIA",
    teamKorean: "KIA",
    stats: { avg: 0.318, hits: 156, homeRuns: 38, rbi: 108, runs: 89 },
  },
  {
    id: "kia-kim-gyu-sung",
    name: "김규성",
    number: 14,
    position: "내야수",
    team: "KIA",
    teamKorean: "KIA",
    stats: { avg: 0.234, hits: 56, homeRuns: 9, rbi: 32, runs: 38 },
  },
  {
    id: "kia-park-min",
    name: "박민",
    number: 2,
    position: "내야수",
    team: "KIA",
    teamKorean: "KIA",
    stats: { avg: 0.301, hits: 134, homeRuns: 26, rbi: 84, runs: 78 },
  },
  {
    id: "kia-kim-sun-bin",
    name: "김선빈",
    number: 3,
    position: "내야수",
    team: "KIA",
    teamKorean: "KIA",
    stats: { avg: 0.278, hits: 98, homeRuns: 17, rbi: 62, runs: 69 },
  },
  {
    id: "kia-wisdom",
    name: "위즈덤",
    number: 45,
    position: "내야수",
    team: "KIA",
    teamKorean: "KIA",
    stats: { avg: 0.267, hits: 89, homeRuns: 12, rbi: 45, runs: 52 },
  },
  {
    id: "kia-oh-sun-woo",
    name: "오선우",
    number: 56,
    position: "내야수",
    team: "KIA",
    teamKorean: "KIA",
    stats: { avg: 0.289, hits: 123, homeRuns: 18, rbi: 67, runs: 74 },
  },
  {
    id: "kia-jung-hae-won",
    name: "정해원",
    number: 64,
    position: "내야수",
    team: "KIA",
    teamKorean: "KIA",
    stats: { avg: 0.312, hits: 145, homeRuns: 32, rbi: 95, runs: 82 },
  },
  {
    id: "kia-yoon-do-hyun",
    name: "윤도현",
    number: 9,
    position: "내야수",
    team: "KIA",
    teamKorean: "KIA",
    stats: { avg: 0.234, hits: 56, homeRuns: 7, rbi: 28, runs: 35 },
  },

  {
    id: "kia-kim-ho-ryung",
    name: "김호령",
    number: 27,
    position: "외야수",
    team: "KIA",
    teamKorean: "KIA",
    stats: { avg: 0.318, hits: 156, homeRuns: 35, rbi: 102, runs: 89 },
  },
  {
    id: "kia-choi-hyung-woo",
    name: "최형우",
    number: 34,
    position: "외야수",
    team: "KIA",
    teamKorean: "KIA",
    stats: { avg: 0.267, hits: 89, homeRuns: 14, rbi: 48, runs: 55 },
  },
  {
    id: "kia-kim-seok-hwan",
    name: "김석환",
    number: 35,
    position: "외야수",
    team: "KIA",
    teamKorean: "KIA",
    stats: { avg: 0.289, hits: 123, homeRuns: 21, rbi: 72, runs: 68 },
  },
  {
    id: "kia-park-jae-hyun",
    name: "박재현",
    number: 36,
    position: "외야수",
    team: "KIA",
    teamKorean: "KIA",
    stats: { avg: 0.234, hits: 56, homeRuns: 9, rbi: 31, runs: 42 },
  },
  {
    id: "kia-na-sung-bum",
    name: "나성범",
    number: 47,
    position: "외야수",
    team: "KIA",
    teamKorean: "KIA",
    stats: { avg: 0.278, hits: 98, homeRuns: 16, rbi: 58, runs: 64 },
  },

  // 두산 베어스
  {
    id: "doo-park-chi-guk",
    name: "박치국",
    number: 1,
    position: "투수",
    team: "DOO",
    teamKorean: "두산",
    stats: { era: 3.45, wins: 11, losses: 7, strikeouts: 142 },
  },
  {
    id: "doo-hong-gun-hee",
    name: "홍건희",
    number: 17,
    position: "투수",
    team: "DOO",
    teamKorean: "두산",
    stats: { era: 4.12, wins: 8, losses: 9, strikeouts: 98 },
  },
  {
    id: "doo-kim-min-gyu",
    name: "김민규",
    number: 19,
    position: "투수",
    team: "DOO",
    teamKorean: "두산",
    stats: { era: 2.87, wins: 16, losses: 4, strikeouts: 178 },
  },
  {
    id: "doo-lee-byung-hun",
    name: "이병헌",
    number: 29,
    position: "투수",
    team: "DOO",
    teamKorean: "두산",
    stats: { era: 3.78, wins: 10, losses: 6, strikeouts: 125 },
  },
  {
    id: "doo-kim-jung-woo",
    name: "김정우",
    number: 30,
    position: "투수",
    team: "DOO",
    teamKorean: "두산",
    stats: { era: 3.21, wins: 13, losses: 5, strikeouts: 165 },
  },
  {
    id: "doo-jack-log",
    name: "잭로그",
    number: 39,
    position: "투수",
    team: "DOO",
    teamKorean: "두산",
    stats: { era: 4.45, wins: 6, losses: 10, strikeouts: 89 },
  },
  {
    id: "doo-kwak-bin",
    name: "곽빈",
    number: 47,
    position: "투수",
    team: "DOO",
    teamKorean: "두산",
    stats: { era: 3.67, wins: 9, losses: 7, strikeouts: 118 },
  },
  {
    id: "doo-park-shin-ji",
    name: "박신지",
    number: 49,
    position: "투수",
    team: "DOO",
    teamKorean: "두산",
    stats: { era: 4.01, wins: 7, losses: 8, strikeouts: 95 },
  },
  {
    id: "doo-lee-young-ha",
    name: "이영하",
    number: 50,
    position: "투수",
    team: "DOO",
    teamKorean: "두산",
    stats: { era: 3.54, wins: 11, losses: 5, strikeouts: 142 },
  },
  {
    id: "doo-cole-irvin",
    name: "콜어빈",
    number: 57,
    position: "투수",
    team: "DOO",
    teamKorean: "두산",
    stats: { era: 4.23, wins: 5, losses: 11, strikeouts: 76 },
  },
  {
    id: "doo-choi-won-jun",
    name: "최원준",
    number: 61,
    position: "투수",
    team: "DOO",
    teamKorean: "두산",
    stats: { era: 3.89, wins: 8, losses: 7, strikeouts: 108 },
  },
  {
    id: "doo-kim-taek-yeon",
    name: "김택연",
    number: 63,
    position: "투수",
    team: "DOO",
    teamKorean: "두산",
    stats: { era: 3.12, wins: 12, losses: 6, strikeouts: 165 },
  },
  {
    id: "doo-yoon-tae-ho",
    name: "윤태호",
    number: 65,
    position: "투수",
    team: "DOO",
    teamKorean: "두산",
    stats: { era: 4.56, wins: 4, losses: 12, strikeouts: 67 },
  },
  {
    id: "doo-choi-min-seok",
    name: "최민석",
    number: 68,
    position: "투수",
    team: "DOO",
    teamKorean: "두산",
    stats: { era: 3.78, wins: 9, losses: 8, strikeouts: 125 },
  },
  {
    id: "doo-lee-gyo-hoon",
    name: "이교훈",
    number: 7,
    position: "투수",
    team: "DOO",
    teamKorean: "두산",
    stats: { era: 4.34, wins: 6, losses: 9, strikeouts: 82 },
  },
  {
    id: "doo-yang-jae-hoon",
    name: "양재훈",
    number: 92,
    position: "투수",
    team: "DOO",
    teamKorean: "두산",
    stats: { era: 2.76, wins: 18, losses: 3, strikeouts: 189 },
  },

  {
    id: "doo-park-sung-jae",
    name: "박성재",
    number: 15,
    position: "포수",
    team: "DOO",
    teamKorean: "두산",
    stats: { avg: 0.278, hits: 95, homeRuns: 13, rbi: 52, runs: 44 },
  },
  {
    id: "doo-yang-eui-ji",
    name: "양의지",
    number: 25,
    position: "포수",
    team: "DOO",
    teamKorean: "두산",
    stats: { avg: 0.245, hits: 67, homeRuns: 8, rbi: 34, runs: 31 },
  },
  {
    id: "doo-kim-gi-yeon",
    name: "김기연",
    number: 45,
    position: "포수",
    team: "DOO",
    teamKorean: "두산",
    stats: { avg: 0.289, hits: 123, homeRuns: 19, rbi: 68, runs: 72 },
  },

  {
    id: "doo-lee-yu-chan",
    name: "이유찬",
    number: 13,
    position: "내야수",
    team: "DOO",
    teamKorean: "두산",
    stats: { avg: 0.318, hits: 156, homeRuns: 38, rbi: 108, runs: 89 },
  },
  {
    id: "doo-park-gye-beom",
    name: "박계범",
    number: 14,
    position: "내야수",
    team: "DOO",
    teamKorean: "두산",
    stats: { avg: 0.234, hits: 56, homeRuns: 9, rbi: 32, runs: 38 },
  },
  {
    id: "doo-kang-seung-ho",
    name: "강승호",
    number: 23,
    position: "내야수",
    team: "DOO",
    teamKorean: "두산",
    stats: { avg: 0.301, hits: 134, homeRuns: 26, rbi: 84, runs: 78 },
  },
  {
    id: "doo-kim-dong-jun",
    name: "김동준",
    number: 48,
    position: "내야수",
    team: "DOO",
    teamKorean: "두산",
    stats: { avg: 0.278, hits: 98, homeRuns: 17, rbi: 62, runs: 69 },
  },
  {
    id: "doo-park-jun-soon",
    name: "박준순",
    number: 52,
    position: "내야수",
    team: "DOO",
    teamKorean: "두산",
    stats: { avg: 0.267, hits: 89, homeRuns: 12, rbi: 45, runs: 52 },
  },
  {
    id: "doo-oh-myung-jin",
    name: "오명진",
    number: 6,
    position: "내야수",
    team: "DOO",
    teamKorean: "두산",
    stats: { avg: 0.289, hits: 123, homeRuns: 18, rbi: 67, runs: 74 },
  },
  {
    id: "doo-ahn-jae-seok",
    name: "안재석",
    number: 62,
    position: "내야수",
    team: "DOO",
    teamKorean: "두산",
    stats: { avg: 0.312, hits: 145, homeRuns: 32, rbi: 95, runs: 82 },
  },

  {
    id: "doo-kim-min-seok",
    name: "김민석",
    number: 2,
    position: "외야수",
    team: "DOO",
    teamKorean: "두산",
    stats: { avg: 0.318, hits: 156, homeRuns: 35, rbi: 102, runs: 89 },
  },
  {
    id: "doo-jung-soo-bin",
    name: "정수빈",
    number: 31,
    position: "외야수",
    team: "DOO",
    teamKorean: "두산",
    stats: { avg: 0.267, hits: 89, homeRuns: 14, rbi: 48, runs: 55 },
  },
  {
    id: "doo-kim-jae-hwan",
    name: "김재환",
    number: 32,
    position: "외야수",
    team: "DOO",
    teamKorean: "두산",
    stats: { avg: 0.289, hits: 123, homeRuns: 21, rbi: 72, runs: 68 },
  },
  {
    id: "doo-kim-in-tae",
    name: "김인태",
    number: 33,
    position: "외야수",
    team: "DOO",
    teamKorean: "두산",
    stats: { avg: 0.234, hits: 56, homeRuns: 9, rbi: 31, runs: 42 },
  },
  {
    id: "doo-hong-sung-ho",
    name: "홍성호",
    number: 34,
    position: "외야수",
    team: "DOO",
    teamKorean: "두산",
    stats: { avg: 0.278, hits: 98, homeRuns: 16, rbi: 58, runs: 64 },
  },
  {
    id: "doo-jo-soo-haeng",
    name: "조수행",
    number: 51,
    position: "외야수",
    team: "DOO",
    teamKorean: "두산",
    stats: { avg: 0.256, hits: 78, homeRuns: 11, rbi: 41, runs: 49 },
  },
  {
    id: "doo-cave",
    name: "케이브",
    number: 8,
    position: "외야수",
    team: "DOO",
    teamKorean: "두산",
    stats: { avg: 0.301, hits: 134, homeRuns: 24, rbi: 81, runs: 76 },
  },

  // 키움 히어로즈
  {
    id: "kiw-jung-hyun-woo",
    name: "정현우",
    number: 13,
    position: "투수",
    team: "KIW",
    teamKorean: "키움",
    stats: { era: 3.45, wins: 11, losses: 7, strikeouts: 142 },
  },
  {
    id: "kiw-jo-young-gun",
    name: "조영건",
    number: 20,
    position: "투수",
    team: "KIW",
    teamKorean: "키움",
    stats: { era: 4.12, wins: 8, losses: 9, strikeouts: 98 },
  },
  {
    id: "kiw-oh-seok-ju",
    name: "오석주",
    number: 31,
    position: "투수",
    team: "KIW",
    teamKorean: "키움",
    stats: { era: 2.87, wins: 16, losses: 4, strikeouts: 178 },
  },
  {
    id: "kiw-park-yoon-sung",
    name: "박윤성",
    number: 35,
    position: "투수",
    team: "KIW",
    teamKorean: "키움",
    stats: { era: 3.78, wins: 10, losses: 6, strikeouts: 125 },
  },
  {
    id: "kiw-mercedes",
    name: "메르세데스",
    number: 42,
    position: "투수",
    team: "KIW",
    teamKorean: "키움",
    stats: { era: 3.21, wins: 13, losses: 5, strikeouts: 165 },
  },
  {
    id: "kiw-won-jong-hyun",
    name: "원종현",
    number: 46,
    position: "투수",
    team: "KIW",
    teamKorean: "키움",
    stats: { era: 4.45, wins: 6, losses: 10, strikeouts: 89 },
  },
  {
    id: "kiw-kim-sun-gi",
    name: "김선기",
    number: 49,
    position: "투수",
    team: "KIW",
    teamKorean: "키움",
    stats: { era: 3.67, wins: 9, losses: 7, strikeouts: 118 },
  },
  {
    id: "kiw-ha-young-min",
    name: "하영민",
    number: 50,
    position: "투수",
    team: "KIW",
    teamKorean: "키움",
    stats: { era: 4.01, wins: 7, losses: 8, strikeouts: 95 },
  },
  {
    id: "kiw-alcantara",
    name: "알칸타라",
    number: 54,
    position: "투수",
    team: "KIW",
    teamKorean: "키움",
    stats: { era: 3.54, wins: 11, losses: 5, strikeouts: 142 },
  },
  {
    id: "kiw-jeon-jun-pyo",
    name: "전준표",
    number: 62,
    position: "투수",
    team: "KIW",
    teamKorean: "키움",
    stats: { era: 4.23, wins: 5, losses: 11, strikeouts: 76 },
  },
  {
    id: "kiw-kim-sung-min",
    name: "김성민",
    number: 8,
    position: "투수",
    team: "KIW",
    teamKorean: "키움",
    stats: { era: 3.89, wins: 8, losses: 7, strikeouts: 108 },
  },
  {
    id: "kiw-park-jung-hoon",
    name: "박정훈",
    number: 94,
    position: "투수",
    team: "KIW",
    teamKorean: "키움",
    stats: { era: 3.12, wins: 12, losses: 6, strikeouts: 165 },
  },
  {
    id: "kiw-yoon-seok-won",
    name: "윤석원",
    number: 95,
    position: "투수",
    team: "KIW",
    teamKorean: "키움",
    stats: { era: 4.56, wins: 4, losses: 12, strikeouts: 67 },
  },
  {
    id: "kiw-kim-dong-gyu",
    name: "김동규",
    number: 99,
    position: "투수",
    team: "KIW",
    teamKorean: "키움",
    stats: { era: 3.78, wins: 9, losses: 8, strikeouts: 125 },
  },

  {
    id: "kiw-kim-gun-hee",
    name: "김건희",
    number: 12,
    position: "포수",
    team: "KIW",
    teamKorean: "키움",
    stats: { avg: 0.278, hits: 95, homeRuns: 13, rbi: 52, runs: 44 },
  },
  {
    id: "kiw-kim-dong-hun",
    name: "김동헌",
    number: 47,
    position: "포수",
    team: "KIW",
    teamKorean: "키움",
    stats: { avg: 0.245, hits: 67, homeRuns: 8, rbi: 34, runs: 31 },
  },

  {
    id: "kiw-kim-tae-jin",
    name: "김태진",
    number: 1,
    position: "내야수",
    team: "KIW",
    teamKorean: "키움",
    stats: { avg: 0.318, hits: 156, homeRuns: 38, rbi: 108, runs: 89 },
  },
  {
    id: "kiw-song-sung-moon",
    name: "송성문",
    number: 24,
    position: "내야수",
    team: "KIW",
    teamKorean: "키움",
    stats: { avg: 0.234, hits: 56, homeRuns: 9, rbi: 32, runs: 38 },
  },
  {
    id: "kiw-yeom-seung-won",
    name: "염승원",
    number: 39,
    position: "내야수",
    team: "KIW",
    teamKorean: "키움",
    stats: { avg: 0.301, hits: 134, homeRuns: 26, rbi: 84, runs: 78 },
  },
  {
    id: "kiw-choi-ju-hwan",
    name: "최주환",
    number: 53,
    position: "내야수",
    team: "KIW",
    teamKorean: "키움",
    stats: { avg: 0.278, hits: 98, homeRuns: 17, rbi: 62, runs: 69 },
  },
  {
    id: "kiw-oh-sun-jin",
    name: "오선진",
    number: 60,
    position: "내야수",
    team: "KIW",
    teamKorean: "키움",
    stats: { avg: 0.267, hits: 89, homeRuns: 12, rbi: 45, runs: 52 },
  },
  {
    id: "kiw-kwon-hyuk-bin",
    name: "권혁빈",
    number: 71,
    position: "내야수",
    team: "KIW",
    teamKorean: "키움",
    stats: { avg: 0.289, hits: 123, homeRuns: 18, rbi: 67, runs: 74 },
  },
  {
    id: "kiw-song-ji-hoo",
    name: "송지후",
    number: 86,
    position: "내야수",
    team: "KIW",
    teamKorean: "키움",
    stats: { avg: 0.312, hits: 145, homeRuns: 32, rbi: 95, runs: 82 },
  },
  {
    id: "kiw-eo-jun-seo",
    name: "어준서",
    number: 92,
    position: "내야수",
    team: "KIW",
    teamKorean: "키움",
    stats: { avg: 0.234, hits: 56, homeRuns: 7, rbi: 28, runs: 35 },
  },
  {
    id: "kiw-yeo-dong-wook",
    name: "여동욱",
    number: 93,
    position: "내야수",
    team: "KIW",
    teamKorean: "키움",
    stats: { avg: 0.278, hits: 98, homeRuns: 15, rbi: 54, runs: 61 },
  },
  {
    id: "kiw-jeon-tae-hyun",
    name: "전태현",
    number: 97,
    position: "내야수",
    team: "KIW",
    teamKorean: "키움",
    stats: { avg: 0.245, hits: 67, homeRuns: 8, rbi: 32, runs: 38 },
  },

  {
    id: "kiw-park-soo-jong",
    name: "박수종",
    number: 14,
    position: "외야수",
    team: "KIW",
    teamKorean: "키움",
    stats: { avg: 0.318, hits: 156, homeRuns: 35, rbi: 102, runs: 89 },
  },
  {
    id: "kiw-lee-ju-hyung",
    name: "이주형",
    number: 2,
    position: "외야수",
    team: "KIW",
    teamKorean: "키움",
    stats: { avg: 0.267, hits: 89, homeRuns: 14, rbi: 48, runs: 55 },
  },
  {
    id: "kiw-ju-sung-won",
    name: "주성원",
    number: 25,
    position: "외야수",
    team: "KIW",
    teamKorean: "키움",
    stats: { avg: 0.289, hits: 123, homeRuns: 21, rbi: 72, runs: 68 },
  },
  {
    id: "kiw-lim-ji-yeol",
    name: "임지열",
    number: 29,
    position: "외야수",
    team: "KIW",
    teamKorean: "키움",
    stats: { avg: 0.234, hits: 56, homeRuns: 9, rbi: 31, runs: 42 },
  },
  {
    id: "kiw-park-ju-hong",
    name: "박주홍",
    number: 57,
    position: "외야수",
    team: "KIW",
    teamKorean: "키움",
    stats: { avg: 0.278, hits: 98, homeRuns: 16, rbi: 58, runs: 64 },
  },

  // 더 많은 팀들의 선수 데이터를 추가할 수 있습니다...
]

export function getPlayersByTeam(teamCode: string): Player[] {
  return players.filter((player) => player.team === teamCode)
}

export function searchPlayers(query: string): Player[] {
  const lowercaseQuery = query.toLowerCase()
  return players.filter(
    (player) =>
      player.name.toLowerCase().includes(lowercaseQuery) ||
      player.teamKorean.toLowerCase().includes(lowercaseQuery) ||
      player.position.toLowerCase().includes(lowercaseQuery),
  )
}

export function getPlayerById(id: string): Player | undefined {
  return players.find((player) => player.id === id)
}
